apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: demo-apps
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:/SIGqPGVSB7dd2XhVFSF/L5M5wRxMTFW/uDUaRJRp4geq3HL,iv:K/w4GgvFz9gvDaS9JlLeIS/SBt5z6oCZdJHDPwgsXNQ=,tag:PHXWVO3PkK39+sq0cviw+w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:CWBHYQ==,iv:Dm5yXye6kzzF+YNxgc+IIlo7cP6cTEF6ywnq+ykwcbY=,tag:1ZPxUFiKWMEbikpXZIuyLA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Wzvi2e7uLA==,iv:XBdjJ4Jj0d7ggudRXS0aTJdskqHz40f3chRuQPLHpIA=,tag:hmQkVmt3ywr5yqaqqAUtyw==,type:str]
    DB_USER: ENC[AES256_GCM,data:jVu7yYcxvPlM,iv:Yov9IyxuRj9PsudA2m4QADkvMlOvWcqp0XCztAdENLU=,tag:nBoSdg+EFzaC9dTQo15yfg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:RUsHGMSs4mODDRWtbzgOEABitMvUT433lA==,iv:ypkTcnH26AFbFG5Nsg3vgaPKqT3dJR0k3ETFezvtVlY=,tag:fV1rIGzQnozw6be1TSYbbw==,type:str]
sops:
    age:
        - recipient: age1h44rlvy9c2ffytt78msmhjtuyuwtpyc6jje7fgjkg4x7l0hpt5dsfxlf9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdFFnQzVrczhsQjdMN0Z6
            SjFsdUFzQ0tiUk5jVFRMRnFXUExJRWkvYWtrCm1RT2lNTTNxS3d6VnUraGRLNjhE
            eWRZSXpzNGhIa2k0c1B3V3JHSUZTY3cKLS0tIEl6a2tJODBSTlBGUmtTYy82MFpq
            VTN0WjRVVXFBc2pwTHp1YzU3ODYzbjAKlTXl9bzSFxNAutZ9+XIT0yNbV50Uwyoy
            7eIo4xCaF2UTP1s5ylx0dUyiiEH7WeH9P5KYcFRZdezLtlU2q126MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T08:56:21Z"
    mac: ENC[AES256_GCM,data:+0PNxpQ2Pn/3q/UvPLs9gMzN6xPU79XJ2icRLDWpb0xuvP3QNCy6rd+F6I/farK1dcCogh71NibXhSEa35vWhxfZpOE96xOwF0ivA69fiNVDeJ9br1Q6tHwD4E+Y3JLZMPq89gLlu+IOa76i0r56Ac+btMrxWiMhzpZdxsbZdWk=,iv:aP57sP1QtvCjeKAcglbBAXW6kUg/iwOSOAzq5HP98Tw=,tag:npm9CaW6yDT//6677Q1TGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
